import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

// Load DM Sans font with Latin subset
const dmSans = DM_Sans({
  subsets: ["latin"],
});

// Metadata for the application (used for SEO and page <head> elements)
export const metadata: Metadata = {
  title: "Create Next App", // Default page title
  description: "Generated by create next app", // Default meta description
};

// RootLayout – Main layout wrapping all pages with global font and structure
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Content passed from each route
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        {/* Render all page content within the global font and smoothing settings */}
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
